name: movie_app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  video_player: ^2.7.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

# Splash Screen
flutter_native_splash:
  image: assets/logo.png
  color: "#000000"

flutter:
  assets:
    - assets/logo.png
    - assets/banner.png
    - assets/profile.png

  uses-material-design: true